# -*- coding: utf-8 -*-
"""10.Series.elementlarni tanlash

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YAkxeBMO_F_9Dq5GCalTjfXIcJ8wCySh
"""

import numpy as np
import pandas as pd

data={

    'yil':[2021,2020,2019,2018,2017,2016,2015,2010],
    'aholi soni':[33.9,33.5,32.5,31.9,31.4,30.9,28.5,28.1],
    'temp':[1.54,1.48,1.56,1.62,1.65,1.66,1.64,1.53],
    'zichlik':[79.77,78.68,77.32,76.34,75.13,73.91,72.71,67.03]}

df=pd.DataFrame(data)

df

data=df['aholi soni']
data

type(data)

data=df[['aholi soni']] #ikkita qavs bolsa dataframe bo`ladi
data

type(data)

data[0:4]

obj=pd.Series(np.arange(8.),index=['a','b','c','d','e','f','g','h'])
obj

obj[['a']]

obj[0:4]

obj['a':'f']

obj['a':'c']=15

obj

obj[obj<15]

obj[obj<7]

