# -*- coding: utf-8 -*-
"""11.Dataframe elementlarini tanlash.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9_En5Qqk5ayki05gogX36zmc-ua1G-P
"""

import numpy as np
import pandas as pd

uz={2020:33.5,2019:32.9,2018:32.5,2017:31.9,2016:31.4,2015:30.9}
kz={2020:18.8,2019:18.3,2017:18.1,2016:17.8,2015:17.6}
tj={2020:9.5,2019:9.3,2018:9.1,2017:8.9,2016:8.7,2015:8.5}
kg={2020:6.5,2019:6.3,2017:6.2,2016:6.1,2015:6.0}
tr={2020:6.0,2019:5.9,2018:5.9,2017:5.8,2016:5.6,2015:5.6}

df=pd.DataFrame(
    {'uzbekistan':uz,
     'kazakhstan':kz,
     'tajikistan':tj,
     'kyrgizstan':kg,
     'turkmanistan':tr})

df

df['uzbekistan'].to_numpy()

df[['uzbekistan','turkmanistan']]

df[3:]

df>10

df>20

dfuz=df['uzbekistan']

dfuz[dfuz>32]

df

df2=df.transpose(copy=True)

df2

df2[df2[2015]<8]

