# -*- coding: utf-8 -*-
"""12.loc/iloc va at/iat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpcXZq8paMifyVXqT5rH43VaCmRTzpjf
"""

import numpy as np
import pandas as pd

uz={2020:33.5,2019:32.9,2018:32.5,2017:31.9,2016:31.4,2015:30.9}
kz={2020:18.8,2019:18.3,2017:18.1,2016:17.8,2015:17.6}
tj={2020:9.5,2019:9.3,2018:9.1,2017:8.9,2016:8.7,2015:8.5}
kg={2020:6.5,2019:6.3,2017:6.2,2016:6.1,2015:6.0}
tr={2020:6.0,2019:5.9,2018:5.9,2017:5.8,2016:5.6,2015:5.6}

df=pd.DataFrame(
    {'uzbekistan':uz,
     'kazakhstan':kz,
     'tajikistan':tj,
     'kyrgizstan':kg,
     'turkmanistan':tr})

df

# loc va iloc.  funksiyasi
df['kazakhstan']

df.loc[[2019,2020]] # loc funksiyasi qatorlarni ajratib olish uchun kerak

df.loc[[2015,2020],['uzbekistan','tajikistan']]

# iloc bu qatorlarni index orqali ajratib oladi
df.iloc[[0],[0,3]]

s=df.at[2015,'uzbekistan'] # aynan bir qiymatni ko`rsatib beradi
s

n=df.at[2016,'uzbekistan']
n

s-n

df.iat[2,2]

df

numb=list(range(10,21))
numb

numb[0]

numb[-1]

obj=pd.Series(np.arange(10.))
obj

obj[0]

obj[-1]# numpyda -1 index bilan murojaat qilib bolmaydi manfiy bazida

ser=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
ser

ser[-1] #agar index harf bo`lsa manfiy indexdan foydalanib chaqirish mumkin

ser.iloc[-1]

