# -*- coding: utf-8 -*-
"""13.arifmetik amallar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQZlFAmCEQ2WTWo6Sw68fJQyczceAJ_j
"""

#arifmetik amallar
import numpy as np
import pandas as pd

s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

s1

s2

s1+s2

df1=pd.DataFrame(np.arange(9.0).reshape(3,3),columns=list('bcd'),index=['olma','anor','uzum'])
df1

df2=pd.DataFrame(np.arange(12.0).reshape(4,3),columns=list('abc'),index=['olma','anor','qovun','anjir'])
df2

df1+df2

df1.add(df2,fill_value=0)

df2.sub(df1,fill_value=0)

df2.rsub(df1,fill_value=0)# teskarisga ayradi

df2.div(df1)

df2.rdiv(df1)

df=pd.DataFrame(np.arange(1,13.).reshape(3,4),index=list('abc'),columns=['olma','anor','qovun','anjir'])
obj=pd.Series([1,1,2,3],index=df.columns)

df

obj

df+obj

obj1=pd.Series([1,2,3],index=['olma','uzum','qovun'])

df.sub(obj1)

obj1.sub(df)

df

obj['olma']

df+obj['olma']

