# -*- coding: utf-8 -*-
"""14.arifmetics practices in pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129dvPjdEOl61SIjzIM-_88XLRK_SwMdV
"""

import numpy as np
import pandas as pd

df=pd.DataFrame(np.random.randn(3,4),index=list("abc"),columns=['olma','anor','anjir','gilos'])
df

np.abs(df)

df2=np.round(df)

df.apply(np.abs)

df

df.apply(sum,axis=1)

f=lambda x:x.max()-x.min()

df.apply(f)

def foo(x):
  return pd.Series([x.min(),x.max()],index=['min','max'])

df.apply(foo)

df

df2.applymap(lambda x:x*x)

