# -*- coding: utf-8 -*-
"""15.sorting and ranking

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xfA8jF0mw2Ejls8KGZLCLfa5iNpgQCa
"""

import numpy as np
import pandas as pd

obj=pd.Series(range(4),index=['a','b','s','d'])
obj

obj.sort_index()

obj.sort_values()

df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df

df.sort_index(axis=1)

df.sort_index(axis=1,inplace=True)

df

df.sort_index(axis=1,ascending=False)

df

df.sort_values(by='price',ascending=False)

df.sort_values(by=['price','mileage'],ascending=False)

