# -*- coding: utf-8 -*-
"""16. to Rating

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jIJ97pVMM_b6XKombTzjXDQHnn02Jt2g
"""

import numpy as np
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df

df['rating']=df['year'].rank()
df

df.sort_values('year')

df['rating']=df['price'].rank(method='min')

df.sort_values('price')

df['rating']=df['mileage'].rank(method='average')

df.sort_values('mileage')

df['rank']=df['price'].rank()

df.sort_values('price')

df['ranky']=df['lot'].rank()

df.sort_values('lot')

