# -*- coding: utf-8 -*-
"""1.1 creating series from dictionary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X0YgbofaCGy_ktX9qWmtvMSOcbC-nmmz
"""

import pandas as pd
import numpy as np

cars_dic={'mqlibu':40000,'lasetti':20000,'toyota':45000,'mazda':52000,'honda':38000}
type(cars_dic)

cars1=pd.Series(cars_dic)
cars1

'mqlibu' in cars1

cars_dic

models=['honda','toyota','lasetti','jaguar','malibu','toyota']

cars2=pd.Series(cars_dic,index=models)

cars2

