# -*- coding: utf-8 -*-
"""1 Pandas library

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYo6kIzJsDFI9c-r_aVOOHx1GzJUXmaz
"""

import pandas as pd
import numpy as np

"""series() malumotlar tuzilmasi"""

from pandas import Series

obj=Series([4,5,6,-7])
type(obj)

print(obj)

obj.values

obj.index

obj[0]

obj2=Series([6,8,9,10,-6.7],index=['a','b','c','d','e'])

print(obj2)

obj2[['a','b','c']]

obj2[obj2>2]

obj2*2

np.exp(obj2)

# vazifa
obj3=pd.Series([45,78,90,55,88],index=['ali','vali','hasan','jasur','madina'])
print(obj3)

passed=obj3>=60
print(passed)
passed

ort=obj3.mean()
ort

obj3.idxmax()

