# -*- coding: utf-8 -*-
"""2 series () methods

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MYi5LAeiIFTks41b3y-ssYAgODHywJTm
"""

import numpy as np
import pandas as pd
from pandas import Series

cars_dic={'malibu':40000,'lasetti':20000,'toyota':45000,'mazda':52000,'honda':38000}

cars1=Series(cars_dic)

models=['honda','toyota','lasetti','jaguar','malibu','toyota']

cars2=pd.Series(cars_dic,index=models)
cars2

cars2.isnull()

cars2.notnull()

cars1

cars1+cars2

cars2.name="avtosalon"

cars2.index.name="modellar"

cars2

cars2.is_unique

cars2

cars2.iloc[2]#ma`lumotlarga index raqami boyicha murojaat qilish

cars2.iloc[-1]

