# -*- coding: utf-8 -*-
"""3 dataframe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bywj-X-iyeJTRYbILuUyC5pQ0DI2pML9
"""

#DATAFRAME

import pandas as pd

data={
    'yil':[2021,2020,2019,2018,2017,2016,2015,2010],
    'aholi soni':[33.9,33.5,32.9,32.5,31.9,21.4,30.9,28.5],
    'temp':[1.54,1.48,1.56,1.62,1.66,1.64,1.53,2.4]
}

df=pd.DataFrame(data)
df

df.head()# boshidagi 5 ta elementni chiqarada agar ichiga n son yozsak n ta chiqaradi

df.head(7)

df.shape #bu qator va ustunlar sonini hisoblaydi

