# -*- coding: utf-8 -*-
"""4 dataframe ustunlari

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtGJbOVvKnoedZ_5SRbasLpKfoXIBn-p
"""

#dataframe ustunlari
import pandas as pd
data={
    'yil':[2021,2020,2019,2018,2017,2016,2015,2010],
    'aholi soni':[33.9,33.5,32.9,32.5,31.9,21.4,30.9,28.5],
    'temp':[1.54,1.48,1.56,1.62,1.66,1.64,1.53,2.4]
}

df=pd.DataFrame(data)
df

df=pd.DataFrame(data,columns=['yil','temp','aholi soni','yalp mah'])
df.head()

df=pd.DataFrame(data,columns=['yil','temp','aholi soni','yalp'],index=[21,20,19,18,17,16,15,10])
df.head()

#istalgan ustun chiqarish uchun kalit sozdan foydalanamiz

df[['aholi soni','temp']]

#ikkinchi usul
df.temp

df

df.yalp=0

df

val=pd.Series([1700,1650,1300],index=[21,20,10])

df.yalp=val

df

df['1500+']=df.yalp>1500

df

#o`chirish
del df['1500+']

df

