# -*- coding: utf-8 -*-
"""5.lug`atdan dataframe yaratish

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUEku8aXvZ9ZvPwTY8CGeO0nvzj-QKqI
"""

import pandas as pd
import numpy as np

data={
    'uzbekistan':{2021:33.9,2020:33,2019:32.9,2018:32.5,2017:31.9},
    'kazakistan':{2021:18.9,2020:18.7,2019:18.5,2018:18.3,2017:18.1,2016:17.8},

    }
df2=pd.DataFrame(data)

df2

df2.index.name='yil'

df2

df2=pd.DataFrame(data,index=[2021,2019,2017])

df2

df2.T

df2.values

arr=df2.values

type(arr)

