# -*- coding: utf-8 -*-
"""6- dataframe ustunlari

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYTBSO3O0YAu9SwPB09Buqgv-z5y3cta
"""

import numpy as np
import pandas as pd

data={
    'uzbekistan':{2021:33.9,2020:33,2019:32.9,2018:32.5,2017:31.9},
    'kazakistan':{2021:18.9,2020:18.7,2019:18.5,2018:18.3,2017:18.1,2016:17.8},

    }
df2=pd.DataFrame(data)

df2

'tajikistan' in df2.columns

2021 in df2.index

df2.index

df2.index[0]

df2

