# -*- coding: utf-8 -*-
"""7.index metodlar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCfz4Id_4jtC2S1KxMCACqQIaOwkavrX
"""

import numpy as np
import pandas as pd

usernames={'anvar':'anvarbek223','olim':'olimtoy','maryam':"mary334455",'javohir':'javohir445'}
emails={'anvar':'anvar@gmail.com','olim':'olim@mail.ru','maryam':'maryam33@gmail.com','javohir':'javohir445@gmail.com'}
data={
    'username':usernames,
    'email':emails
}
df=pd.DataFrame(data)

df

df.index

data2={
    'username':{'olim':'olimjon21','maryam':'maryam2020'},
    'email':{'olim':'olimjon21@mail.ru','maryam':'maryam20@gmail.com'}
    }

df2 = pd.concat([df, pd.DataFrame(data2)])

df2

df2.index

newind=pd.Index(['olim','nafisa','hamida'])

newind

newind.isin(df2.index)

df2.index.difference(newind)

newind.difference(df2.index)

df2.index.union(newind)

df2.index.delete(0)

newind.drop('hamida')

df2.index.delete(0)

df2

df2.index.delete(1)

df2

df2.drop('olim')

df2

df2.index.insert(5,'masha')

df2

df2.index.insert(0,'anvar')

df2.index.is_monotonic_increasing

df2.index.is_unique

newind.is_unique

df2.index.unique()

