# -*- coding: utf-8 -*-
"""8.qayta indexlash

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npVcvOySXrRdMDbXxw21An5Bd_Au3lHT
"""

import numpy as np
import pandas as pd

data={

    'yil':[2021,2020,2019,2018,2017,2016,2015,2010],
    'aholi soni':[33.9,33.5,32.5,31.9,31.4,30.9,28.5,28.1],
    'temp':[1.54,1.48,1.56,1.62,1.65,1.66,1.64,1.53],
    'zichlik':[79.77,78.68,77.32,76.34,75.13,73.91,72.71,67.03]}

df=pd.DataFrame(data)

df

df.index=[21,20,19,18,17,16,15,10]
df

#reindex
ind=[21,20,19,18,17,16,15,10]
ind.sort()
ind

df.reindex(ind) #yangi dataframe qaytaradi

df.reindex([10,15,20])

df.reindex(index=range(10,22),method='nearest')

df.reindex(index=range(10,22),method='ffill')

df

df2=df.reindex(columns=['aholi soni','temp','zichlik'])
df2

df2.sample(3)# istalgan random 3 qatorni chiqari beradi

#loc
df.loc[[10,15,18,20],['aholi soni','temp','zichlik']] # loc kerakli ustun va qatorlarni ajratib olish mumkin

