# -*- coding: utf-8 -*-
"""9 df.drop metodi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dDwJ3t-ZzKUag_kAm55tNN_8DdDiwEe
"""

import numpy as np
import pandas as pd

data={

    'yil':[2021,2020,2019,2018,2017,2016,2015,2010],
    'aholi soni':[33.9,33.5,32.5,31.9,31.4,30.9,28.5,28.1],
    'temp':[1.54,1.48,1.56,1.62,1.65,1.66,1.64,1.53],
    'zichlik':[79.77,78.68,77.32,76.34,75.13,73.91,72.71,67.03]}

df=pd.DataFrame(data)

df

df.index=[21,20,19,18,17,16,15,10]
df

df2=df.drop(10)

df2

df.drop([15,20])

df

